github:
  prebuilds:
    main: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Pull docker images and set up
    init: >
      docker-compose pull &&
      docker-compose up -d &&
      gp sync-done setup
    
  - name: Producer
    init: gp sync-await setup
    command: docker-compose exec broker bash 
    openMode: split-bottom
    
  - name: Consumer
    init: gp sync-await setup
    command: docker-compose exec broker bash 
    openMode: split-right


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
