github:
  prebuilds:
    main: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Pull docker images and set up
    before: docker-compose pull
    command: docker-compose up -d
  - name: Producer
    command: ls
    openMode: split-right


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
